### URL
db.URL.MYSQL=jdbc:mysql://localhost:3306/bd_coches?useSSL=false&serverTimezone=UTC&user=root&password=
db.URL.SQLITE=jdbc:sqlite:basedatos.db

### CSV
CSVFileDefault=./FicheroDeCarga/BBDD Coches.csv

### Informes
rutaInforme=./mi_informe.txt